
deploy-master:
  only:
    - master
  image: node:16-alpine
  cache:
    paths:
      - node_modules
      - .yarn
  stage: deploy
  environment:
    name: prodduction
  script:
    - apk add aws-cli
    - aws --version
    - yarn
    - yarn build
    - aws s3 sync build s3://${S3_BUCKET} --delete;
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION} --paths '/*'
    - 'echo website Deployed successfully to https://${S3_BUCKET}'
